### PR TITLE
Fix: R48xx: only interlock against battery-powered inverters

### LINKED ISSUE #1609: [Bug] Huawei R4850 startet das Laden nicht
### Discussed in https://github.com/hoylabs/OpenDTU-OnBattery/discussions/1607

<div type='discussions-op-text'>

<sup>Originally posted by **tstrempel1980** February  5, 2025</sup>
Hallo zusammen,
ich nutze das CAN Joly Board, Pin mapping habe ich angepasst. Jumper gesetzt.
Der Laderegler soll den Marstek B2500 laden.
Die Entladung abends erfolgt über den HM-600.
OpenDTU on Battery Version: 2025.01.23

warum wird der Laderegler nicht aktiviert?
Ich habe über einen längeren Zeitraum -300 Watt.
Und was bedeutet "disable PSU"

[DPL] requesting 0 W from 0 battery-powered inverters currently producing 0 W (diff 0 W, hysteresis 5 W)
11:23:22.616 > [DPL inverter 114184518511]:
11:23:22.682 >     solar-powered, producing 43 W
11:23:22.743 >     lower/current/upper limit: 50/49/600 W, output capability: 600 W
11:23:22.810 >     sending commands enabled, reachable, eligible
11:23:22.869 >     max reduction production/standby: 0/0 W, max increase: 0 W
11:23:22.936 >     target limit/output/state: -1 W (unchanged)/43 W/unchanged, 0 update timeouts
11:23:22.999 >     MPPTs AC power: a: 21 W b: 23 W
11:23:23.058 > Fetch inverter: 114184518511
11:23:23.123 > Queue size - NRF: 1 CMT: 0
11:23:23.186 > Last missing
11:23:23.248 > Request retransmit: 3
11:23:23.313 > Middle missing
11:23:23.479 > Request retransmit: 1
11:23:23.533 > [Huawei::Controller] Inverter is active, disable PSU
11:23:23.685 > [Huawei::HwIfc] [60.452] InputTemperature: 24.00°C
11:23:23.735 > [Huawei::HwIfc] [60.451] OutputTemperature: 23.00°C
11:23:23.788 > [Huawei::HwIfc] [60.450] InputVoltage: 231.34V
11:23:23.845 > [Huawei::HwIfc] [60.448] OutputCurrentMax: 0.00A
11:23:23.894 > [Huawei::HwIfc] [60.442] InputFrequency: 50.03Hz
11:23:23.964 > [Huawei::HwIfc] [60.453] OutputCurrent: 0.00A
11:23:24.025 > [Huawei::HwIfc] [60.441] InputPower: 0.00W
11:23:24.083 > [Huawei::HwIfc] [60.443] InputCurrent: 0.00A
11:23:24.146 > [Huawei::HwIfc] [60.445] OutputPower: 0.00W
11:23:24.217 > [Huawei::HwIfc] [60.446] Efficiency: 0.00
11:23:24.272 > [Huawei::HwIfc] [60.447] OutputVoltage: 1.77V
11:23:24.335 > Middle missing
11:23:24.399 > Request retransmit: 1
11:23:24.460 > Middle missing
11:23:24.540 > Request retransmit: 1
11:23:24.603 > Fetch inverter: 114184518511
11:23:24.665 > Queue size - NRF: 1 CMT: 0
11:23:24.744 > [DPL] targeting 0 W, base load is 200 W, power meter reads -167.9 W (valid)
11:23:24.881 > [DPL] inverter 114184518511 is behind power meter producing 43 W
11:23:24.948 > [DPL] requesting 0 W from 1 solar-powered inverter currently producing 43 W (diff -43 W, hysteresis 5 W)
11:23:24.999 > [DPL] will cover 43 W using 1 solar-powered inverter
11:23:25.064 > [DPL] battery allowance is 0/0 W DC/AC, solar power is 0/0 W DC/AC, requested are 0 W AC
11:23:25.126 > [DPL] requesting 0 W from 0 battery-powered inverters currently producing 0 W (diff 0 W, hysteresis 5 W)
11:23:25.188 > [DPL inverter 114184518511]:
11:23:25.254 >     solar-powered, producing 43 W
11:23:25.313 >     lower/current/upper limit: 50/49/600 W, output capability: 600 W
11:23:25.377 >     sending commands enabled, reachable, eligible
11:23:25.442 >     max reduction production/standby: 0/0 W, max increase: 0 W
11:23:25.505 >     target limit/output/state: -1 W (unchanged)/43 W/unchanged, 0 update timeouts
11:23:25.565 >     MPPTs AC power: a: 21 W b: 23 W
11:23:25.732 > Success

Vielen Dank für Eure Hilfe :)</div>

### PR DESCRIPTION
**Pull request by schlimmchen**
Closes #1609.

### CODE REVIEW

File: src/PowerLimiter.cpp [hunk 1]
```diff
@@ -912,9 +912,10 @@ bool PowerLimiterClass::usesBatteryPoweredInverter()
     return false;
 }
 
-bool PowerLimiterClass::isGovernedInverterProducing()
+bool PowerLimiterClass::isGovernedBatteryPoweredInverterProducing()
 {
     for (auto const& upInv : _inverters) {
+        if (upInv->isSolarPowered()) { continue; }
```
Comment (AndreasBoehm) [inline src/PowerLimiter.cpp:918]: I know that my PR is not merged yet but what about smart buffer batteries?

Comment (schlimmchen) [reply src/PowerLimiter.cpp:918]: I thought about them and determined that if we are producing energy from a buffer battery, we shall not charge the (buffer) battery using the R48xx, as the inverter(s) on a buffer battery would not be producing power if we had excess power.

This setup doesn't even make sense, as the buffer battery takes care of charging itself, that's why it's smart, isn't it? That would make your question mood, as we don't support this combination.

If a user has a smart buffer battery **and** a regular battery, and some more solar-powered inverters (at the same DTU or some place else), we should still charge the regular battery using the R48xx if there is excess. Currently we would not, as the inverter at the buffer battery is never put into standby, correct? So... That's an issue, right? We would need to know if buffer-powered inverters are... at their lower limit or "essentially in standby as the DPL determined that the inverter is not needed"?

Comment (AndreasBoehm) [reply src/PowerLimiter.cpp:918]: Sorry but i am not sure if i understood it correctly.

We assume that only regular batteries will be charged suing the R48xx which in turn means that we only check if battery-powered inverters are active. Is that correct?

The buffer-powered inverter is always on, at least when the buffer did not shut it off because of a low SoC or for whatever reason. It will never be turned off by the DTU and probably not put into standby? (I need to read up on when we put a inverter in standby an why)

Comment (schlimmchen) [reply src/PowerLimiter.cpp:918]: Err... now you have me going back and forth...

> We assume that only regular batteries will be charged using the R48xx

Let's make that assumption for now. Then we... also skip the loop we are discussing about when iterating a buffered inverter, right?

Comment (AndreasBoehm) [reply src/PowerLimiter.cpp:918]: Yes, lets skip the loop for solar and buffered inverters.

**Comment by schlimmchen** [comment]
Will rebase onto development after #1606 was merged.

**Comment by schlimmchen** [comment]
@AndreasBoehm Please merge if you approve.

**Review by AndreasBoehm — APPROVED** [review]

**Comment by AndreasBoehm** [comment]
Looks good 👍
