### PR TITLE
Fix: DTU serial change not possible

### LINKED ISSUE #1640: [Bug] changing DTU serial not possible
### What happened?

DTU-Einstellungen -> Seriennummer ändern führt zur Meldung "Benötigte Werte fehlen!"

### To Reproduce Bug

DTU-Einstellungen -> Seriennummer ändern 

### Expected Behavior

Seriennummer übernehmen

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU-OnBattery?

2025.02.10

### What firmware variant (PIO Environment)?

generic_esp32s3_usb

### Relevant log/trace output

```Shell

```

### Anything else?

_No response_

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of OpenDTU-OnBattery, not something specific to my installation.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
- [x] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

### PR DESCRIPTION
**Pull request by AndreasBoehm**
Closes #1640

change `serial` to type `string` and add converting wrapper around it.

### CODE REVIEW

File: webapp/src/views/DtuAdminView.vue [hunk 1]
```diff
@@ -8,7 +8,7 @@
             <CardElement :text="$t('dtuadmin.DtuConfiguration')" textVariant="text-bg-primary">
                 <InputElement
                     :label="$t('dtuadmin.Serial')"
-                    v-model="dtuConfigList.serial"
+                    v-model="dtuSerial"
                     type="number"
                     min="1"
                     max="199999999999"
```
Comment (schlimmchen) [inline webapp/src/views/DtuAdminView.vue:14]: Set `type="text"`, remove min and max, revert model. The serial is a hexadecimal string and it should be possible to configure such a hexadecimal serial number.

File: webapp/src/views/DtuAdminView.vue [hunk 2]
```diff
@@ -167,6 +167,14 @@ export default defineComponent({
...
             },
         },
+        dtuSerial: {
+            get(): number {
+                return parseFloat(this.dtuConfigList.serial);
+            },
+            set(value: number) {
+                this.dtuConfigList.serial = value.toString();
+            },
+        },
```
Comment (schlimmchen) [inline webapp/src/views/DtuAdminView.vue:177]: Remove. IMHO this is the wrong approach.

**Review by schlimmchen — CHANGES_REQUESTED** [review]
The DTU serial is a hexadecimal string. The issue is with the input element's config and the type and not with missing conversion between a number and a string.

I was unsure and had to test this myself, so I have the changeset I except ready and will push to this PR now.

**Comment by AndreasBoehm** [comment]
I did not want to change the input from number to string as i expected that there is a strong reason for  using number.

to be honest the whole code around the serial is pretty weird looking for me and doesnt make much sense. In the config we store a uint64_t but for the api we convert it to a string and in the web ui its treated as number.

**Comment by schlimmchen** [comment]
Well, storing it as uint64_t is efficient, I guess that's why Thomas decided to do it like that. Then there is the InputSerial component, and that uses the hex string representation and submits it like a string. That's why I am confident that the error is with the last part: Treating it as a number.

**Comment by schlimmchen** [comment]
@tbnobody Is 94ce7ebb8f0360922555ff7b44273a5b5415d289 the right fix?

**Comment by tbnobody** [comment]
It is not needed to change the serial at all..... the first few characters are not needed.. But only hex values are allowed... and the min and max length of the string is also important.

**Comment by tbnobody** [comment]
On the other hand, the error message "Required values are missing" is shown if some of the POST values are missing.. I remember a bug several versions ago which effected exactly this behavior.

**Comment by schlimmchen** [comment]
> But only hex values are allowed... and the min and max length of the string is also important.

That's why I looked at how the input is converted: `strtoll` is used and then the result is checked to be non-zero. So if the input is not convertible, zero will be returned and catched. If only some chars are converted, the result will be a non-zero uint64_t, which is fine, I guess. If the input is too large, max(int64_t) will be the serial. Still valid, I guess.

> It is not needed to change the serial at all.....

I agree. It is unique per ESP32 and the user has no advantage of changing it as far as I can tell.

Then let's remove the input field and convert it to an information? Maybe even move it to Info -> System -> Card(Radio Information)?

**Comment by tbnobody** [comment]
Not sure about removing.... but i found the issue:
image



First requst works but not the second... Look at the quotation marks of the serial number.

**Comment by tbnobody** [comment]
> My other idea was to use the InputSerial component. How about that?

I also thought about that yes. But in this case the component has to be modified as it does corrently convert HERF serial numbers into hoymiles serial numbers and also parses the serials to show some hint texts.

**Comment by tbnobody** [comment]
If I think about it.... The PR as shown is good but it wood be nice to add a max length to the text field..

**Comment by schlimmchen** [comment]
So what does it take to do it the right way? How about:

1. add to the hint text "serial is a number of 11 hexadecimal digits starting in 1999"
2. do javascript input validation
   * invalid chars
   * invalid length
4. show an Alert if input validation fails
5. abort form submission if input validation fails

Have 2 though 5 be implemented by AI as it's boring/tedious to do by hand :wink:

If we agree on our goal, I think both Andreas and I are willing to prepare the respective changeset.

> it wood be nice to add a max length to the text field..

Well, that's trivial, of course.

**Comment by tbnobody** [comment]
Uhm I think max_length should be 12?

**Comment by tbnobody** [comment]
Looks good!
